spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LMS_DB
    username: postgres  #changed as per Local DB
    password: admin  #changed as per Local DB

app:
  frontend.url: https://lms-frontend.herokuapp.com

# configurations specific to SMTP email
mail:
  host: smtp.gmail.com
  port: 587
  username: info.numpyninja@gmail.com
  password: zzpkpsxuoagmurzy
  protocol: smtp
  #properties.mail.smtp:
  smtp:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com


security:
  app:
    jwtSecret: lmsAppSecretKeyTest
    jwtExpirationMs: 28800000  # 28800000 Ms = 8 hours
    jwtAcctActiveExpMs: 172800000 #2 days in milli seconds
    jwtForgotPasswordExpMs: 7200000 #2 hours in milli seconds

google:
  calendar-id-lms: 42jsfha8fh5t0k9vem1gg8t7fc@group.calendar.google.com
  credentials.file: service_account/credentials.encrypted